doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        entity_managers:
            default:
                mappings:
                    SonataUserBundle: ~
                    FOSUserBundle: ~
        auto_generate_proxy_classes: true
        #naming_strategy: doctrine.orm.naming_strategy.underscore
        #auto_mapping: true
        #mappings:
        #    App:
        #        is_bundle: false
        #        type: annotation
        #        dir: '%kernel.project_dir%/src/Entity'
        #        prefix: 'App\Entity'
        #        alias: App
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
            options: {}
    #types:
    #    json: Sonata\Doctrine\Types\JsonType
    default_database: autoparts
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'
                    alias: App
                SonataUserBundle: ~
                FOSUserBundle: ~
                ApplicationSonataUserBundle: ~