sonata_admin:
    title: 'Sonata Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    assets:
        # javascript paths to add to the page in addition to the list above
        extra_javascripts:
            - assets/js/script.admin.js
    security:
        handler: sonata.admin.security.handler.role


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
