version: "3.7"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.Dockerfile
    volumes:
      - ./www:/var/www/html
      #- ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - fpm
      - mongo
      - mongo-express
    depends_on:
      - fpm

  fpm:
    #image: php:7.2-fpm-alpine
    build:
      context: .
      dockerfile: fpm/.Dockerfile
    environment:
      APP_ENV: dev
    ports:
      - '9000:9000'
    volumes:
      - ./www:/var/www/html
      #- ./fpm/php.ini:/usr/local/etc/php/php.ini
      #- ./fpm/ssmtp.conf:/etc/ssmtp/ssmtp.conf
      #- ./fpm/revaliases:/etc/ssmtp/revaliases
      #- ./cron/docker.sock:/var/run/docker.sock
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - './mongo/data:/data/db'
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: "no"
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
