#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_registration_register:
  controller: App\Controller\RegistrationController::registerAction
  path: /register


fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting

fos_user_profile_edit:
  path: /profile
  controller: App\Controller\ProfileController::editAction

fos_user_resetting_send_email:
  path: /resetting/send-email
  controller: App\Controller\ResettingController::sendEmailAction

check_resetting:
  path: /resetting/check
  controller: App\Controller\ResettingController::checkAction

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /profile

fos_user_security_login:
  path: /login
  controller: App\Controller\UserController::loginAction

fos_user_security_check:
  path: /login_check
  controller: App\Controller\UserController::checkAction

check_phone:
  path: /register/phone_check
  controller: App\Controller\RegistrationController::checkPhoneAction

api_login_check:
  path: /api/login_check

admin_area:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /admin

sonata_user_admin_security:
  resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
  prefix: /admin

sonata_user_admin_resetting:
  resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
  prefix: /admin/resetting

sonata_admin_receipt_orders:
  path:  /admin/receipt/orders
  controller: App\Autoparts\StoreBundle\Controller\StoreAdminController::ordersAction

sonata_admin_receipt_store_items:
  path:  /admin/shipment/store
  controller: App\Autoparts\StoreBundle\Controller\StoreAdminController::storeItemsAction

#gesdinet_jwt_refresh_token:
#  path:       /api/token/refresh
#  controller: gesdinet.jwtrefreshtoken::refresh