# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    mongodb_server: "mongodb://root:root@mongo:27017"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.supplier:
        class: App\Admin\SupplierAdmin
        arguments: [~, App\Document\Supplier, App\Controller\Admin\SupplierAdminController]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: Магазин, label: Supplier }
    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Document\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: Магазин, label: Product }
    admin.order:
        class: App\Admin\OrderItemAdmin
        arguments: [~, App\Document\OrderItem, App\Controller\Admin\OrderItemAdminController]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: Магазин, label: Order }
    admin.account:
        class: App\Admin\PersonalAccountAdmin
        arguments: [~, App\Document\PersonalAccount, ~]
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: sonata_user, label: PersonalAccount }
    #mailer:
    #  alias: fos_user.mailer.noop
    #  public: true

